name: Zeeshan CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Greeting
        run: echo "Hello Zeeshan, workflow is running on main branch!"

      - name: Show Node Version (optional example)
        run: node -v
